import admin from 'firebase-admin';
import { config, logger } from '../config/env.js';
import fs from 'fs';
import path from 'path';

// Check for firebase config file generated by set_up_firebase
const configPath = path.join(process.cwd(), 'firebase-applet-config.json');
let firebaseConfig = {};

if (fs.existsSync(configPath)) {
  firebaseConfig = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
}

if (!admin.apps.length) {
  try {
    if (config.firebaseCredentials) {
      const creds = JSON.parse(config.firebaseCredentials);
      // Fix escaped newlines in private_key (common .env issue)
      if (creds.private_key) {
        creds.private_key = creds.private_key.replace(/\\n/g, '\n');
      }
      admin.initializeApp({
        credential: admin.credential.cert(creds)
      });
    } else {
      // Fallback to default if available (Cloud Run managed identity)
      admin.initializeApp();
    }
    logger.info('Firebase Admin initialized successfully');
  } catch (error) {
    logger.error('Failed to initialize Firebase Admin:', error.message);
  }
}

let firestore;
try {
  firestore = admin.firestore();
} catch (error) {
  logger.warn('Firestore service unavailable (API might be disabled):', error.message);
  firestore = null;
}

// Collection references
export const db = firestore ? {
  users: firestore.collection('users'),
  plansCache: firestore.collection('plans_cache'),
  ledger: firestore.collection('ledger'),
  sessions: firestore.collection('sessions'),
  optouts: firestore.collection('optouts')
} : {
  users: null,
  plansCache: null,
  ledger: null,
  sessions: null,
  optouts: null
};

export default admin;
