import admin from 'firebase-admin';
import { config, logger } from '../config/env.js';
import fs from 'fs';
import path from 'path';

// Check for firebase config file generated by set_up_firebase
const configPath = path.join(process.cwd(), 'firebase-applet-config.json');
let firebaseConfig = {};

if (fs.existsSync(configPath)) {
  firebaseConfig = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
}

if (!admin.apps.length) {
  try {
    if (config.firebaseCredentials) {
      admin.initializeApp({
        credential: admin.credential.cert(JSON.parse(config.firebaseCredentials))
      });
    } else {
      // Fallback to default if available (Cloud Run managed identity)
      admin.initializeApp();
    }
    logger.info('Firebase Admin initialized successfully');
  } catch (error) {
    logger.error('Failed to initialize Firebase Admin:', error);
  }
}

const firestore = admin.firestore();

// Collection references
export const db = {
  users: firestore.collection('users'),
  plansCache: firestore.collection('plans_cache'),
  ledger: firestore.collection('ledger'),
  sessions: firestore.collection('sessions')
};

export default admin;
